name: Tests

on:
  push:
    branches:
      - devel
      - master
  pull_request:
    branches:
      - "**"

env:
  FORCE_COLOR: 2

jobs:
  run:
    name: Node
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3.1.0

      - name: Set up Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: "16.x"
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm run testpr

  integration:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Integration Tests
    steps:
      - uses: actions/checkout@v3.1.0
      - run: ./tests/run
